worker_processes 1;
pid /home/sealorl/cbi/network-security-gateway-lab/run/nginx.pid;
error_log /home/sealorl/cbi/network-security-gateway-lab/logs/nginx-error.log info;

events {
    worker_connections 256;
}

http {
    access_log /home/sealorl/cbi/network-security-gateway-lab/logs/nginx-access.log combined;

    upstream lab_backends {
        server 10.10.20.21:8080 max_fails=2 fail_timeout=5s;
        server 10.10.20.22:8080 max_fails=2 fail_timeout=5s;
    }

    server {
        listen 10.10.20.10:80;
        server_name _;

        location = /health {
            access_log off;
            return 200 "proxy healthy\n";
        }

        location / {
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_pass http://lab_backends;
        }
    }
}
